### ISSUE TITLE
Feature request: `showPrompt`

### ISSUE THREAD

**Issue by papb** [Richienb/dialogy#1]
**Is your feature request related to a problem? Please describe.**

I want a simple UI for the user to input text data

**Describe the solution you'd like**

A `showPrompt` function

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by Richienb** [comment]
`dialogy.input` has been released in [0.2.0](https://www.npmjs.com/package/dialogy/v/0.2.0)

**Comment by papb** [comment]
Awesome! Thank you very much!! :rocket:

**Comment by papb** [comment]
@Richienb I have noticed that calling `input` is considerably slower than the other methods, such as `openFile` and `alert`. Do you know what could be causing this?

**Comment by Richienb** [comment]
@papb Behind the scenes, I'm calling [`tinyfiledialogs::input_box`](https://docs.rs/tinyfiledialogs/3.3.10/tinyfiledialogs/fn.input_box.html). In turn, it's that function that calls the native APIs.

**Comment by papb** [comment]
@Richienb Thanks. Do you also experience slowness with `dialogy.input`?

**Comment by Richienb** [comment]
I'm using Windows 10, and for me, it's opening perfectly fine.

**Comment by papb** [comment]
@Richienb Hmm, I just tried on another computer and it was fine as well. Probably something weird going on with the first PC... Thank you very much!!
